server:
  # 项目服务配置
  port: ${token.server.port}

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      # mysql配置
      driver-class-name: ${token.datasource.driver-class-name}
      url: jdbc:mysql://${token.datasource.host}:${token.datasource.port}/${token.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${token.datasource.username}
      password: ${token.datasource.password}

logging:
  # logging配置
  level:
    com:
      token:
        mapper: debug
        service: info
        controller: info

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.token.entity
  configuration:
    map-underscore-to-camel-case: true